Repository google/benchmark, pull requests merged in 2020-08, with the labels that each got.

#1013 Create build-and-test.yml
  .github/workflows/build-and-test.yml
Labels: cla: yes

#997 Remove "BENCHMARK_" prefix from env var version of CLI flags
  src/commandlineflags.cc
  test/commandlineflags_gtest.cc
Labels: cla: yes, next-release

#1017 Update build instructions to better use CMake
  README.md
Labels: cla: yes

#1029 Add CartesianProduct with associated test
  AUTHORS
  CONTRIBUTORS
  README.md
  include/benchmark/benchmark.h
  src/benchmark_register.cc
  test/CMakeLists.txt
  test/args_product_test.cc
Labels: cla: yes, enhancement

#1021 Fix Clang builds on Windows
  CMakeLists.txt
  cmake/CXXFeatureCheck.cmake
Labels: bug, cla: yes

#1032 Adds -lm linker flag for FreeBSD/OpenBSD and uses github.com/bazelbuil…
  BUILD.bazel
  WORKSPACE
Labels: cla: yes
