Repository google/benchmark, pull requests merged in 2020-11, with the labels that each got.

#1069 Rename 'mftbl' to 'mftb'
  CONTRIBUTORS
  src/cycleclock.h
Labels: bug, cla: yes

#982 bazel support for tools
  WORKSPACE
  requirements.txt
  tools/BUILD.bazel
Labels: cla: yes, enhancement, help wanted

#1054 Added support for macro expansion in benchmark names
  include/benchmark/benchmark.h
  test/fixture_test.cc
Labels: cla: yes

#1071 Disable lto-type-mismatch warnings
  CMakeLists.txt
Labels: bug, cla: yes, next-release

#1073 Fix Range when starting at zero
  src/benchmark_register.h
  test/benchmark_gtest.cc
Labels: cla: yes
