Repository google/benchmark, pull requests merged in 2021-06, with the labels that each got.

#1160 Fix perf counter argument parsing
  AUTHORS
  CONTRIBUTORS
  src/string_util.cc
  test/string_util_gtest.cc
Labels: cla: yes

#1161 Revert "Implementation of random interleaving. (#1105)"
  README.md
  docs/random_interleaving.md
  src/benchmark.cc
  src/benchmark_adjust_repetitions.cc
  src/benchmark_adjust_repetitions.h
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_runner.cc
  src/benchmark_runner.h
  test/CMakeLists.txt
  test/benchmark_random_interleaving_gtest.cc
Labels: cla: yes, next-release

#1164 Introduce "family index" field into JSON output
  include/benchmark/benchmark.h
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_register.cc
  src/benchmark_runner.cc
  src/complexity.cc
  src/json_reporter.cc
  src/statistics.cc
  test/BUILD
  test/complexity_test.cc
  test/filter_test.cc
  test/memory_manager_test.cc
  test/repetitions_test.cc
  test/reporter_output_test.cc
  test/user_counters_tabular_test.cc
  test/user_counters_test.cc
  test/user_counters_thousands_test.cc
Labels: cla: yes

#1165 Introduce per-family instance index
  include/benchmark/benchmark.h
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_register.cc
  src/benchmark_runner.cc
  src/complexity.cc
  src/json_reporter.cc
  src/statistics.cc
  test/complexity_test.cc
  test/memory_manager_test.cc
  test/repetitions_test.cc
  test/reporter_output_test.cc
  test/user_counters_tabular_test.cc
  test/user_counters_test.cc
  test/user_counters_thousands_test.cc
Labels: cla: yes

#1166 Make 'complexity reports' cache per-family, not global
  src/benchmark.cc
  src/benchmark_runner.cc
Labels: cla: yes

#1168 compare.py: sort the results
  tools/compare.py
  tools/gbench/Inputs/test4_run.json
  tools/gbench/report.py
  tools/gbench/util.py
Labels: cla: yes

#1169 Fix leak in test, and provide path to remove leak from library
  README.md
  include/benchmark/benchmark.h
  src/benchmark.cc
  test/benchmark_gtest.cc
Labels: cla: yes

#1163 Random interleaving of benchmark repetitions - the sequel (fixes #1051)
  README.md
  docs/random_interleaving.md
  include/benchmark/benchmark.h
  src/benchmark.cc
  src/benchmark_api_internal.h
  src/benchmark_register.cc
  src/benchmark_runner.cc
  src/benchmark_runner.h
  test/CMakeLists.txt
  test/benchmark_random_interleaving_gtest.cc
Labels: cla: yes

#1167 Enable various sanitizer builds in github actions
  .github/workflows/sanitizer.yml
  .libcxx-setup.sh
  .travis.yml
Labels: cla: yes

#1171 Use modern clang/libc++ for sanitizers
  .github/.libcxx-setup.sh
  .github/workflows/sanitizer.yml
  .libcxx-setup.sh
Labels: cla: yes

#1173 Add support for new architecture loongarch
  src/cycleclock.h
Labels: cla: yes

#1174 [NFCI] Drop warning to satisfy clang's -Wunused-but-set-variable diag
  src/complexity.cc
Labels: cla: yes

#1178 benchmark_runner.h: Remove superfluous semicolon
  src/benchmark_runner.h
Labels: cla: yes

#1179 Provide helpers to create integer lists for the given ranges.
  README.md
  include/benchmark/benchmark.h
  src/benchmark_register.cc
Labels: cla: yes, enhancement

#1182 Add missing trailing commas
  src/json_reporter.cc
Labels: cla: yes

#1185 Move flags inside the `benchmark` namespace
  src/benchmark.cc
  src/benchmark_runner.h
  test/benchmark_random_interleaving_gtest.cc
Labels: cla: yes

#1186 prefix macros to avoid clashes
  src/benchmark.cc
  src/benchmark_register.cc
  src/benchmark_register.h
  src/benchmark_runner.cc
  src/benchmark_runner.h
  src/check.h
  src/colorprint.cc
  src/commandlineflags.h
  src/complexity.cc
  src/csv_reporter.cc
  src/mutex.h
  src/perf_counters.h
  src/re.h
  src/reporter.cc
  src/statistics.cc
  src/sysinfo.cc
  src/thread_timer.h
  src/timers.cc
  test/benchmark_random_interleaving_gtest.cc
  test/output_test.h
  test/output_test_helper.cc
  test/perf_counters_gtest.cc
  test/register_benchmark_test.cc
  test/skip_with_error_test.cc
Labels: cla: yes

#1187 prefix VLOG
  src/benchmark_runner.cc
  src/log.h
  test/output_test_helper.cc
Labels: cla: yes

#1189 Deduplicate test function name in python bindings example
  bindings/python/google_benchmark/example.py
Labels: cla: yes

#1192 Bazel qnx
  BUILD.bazel
  README.md
Labels: cla: yes

#1190 Use C++11 atomic_signal_fence for ClobberMemory
  include/benchmark/benchmark.h
Labels: cla: yes

#1193 Fix type warning on certain compilers
  src/benchmark.cc
Labels: cla: yes

#1194 Fix typos
  src/benchmark_runner.cc
  src/sysinfo.cc
Labels: cla: yes

#1195 fix clang-tidy warnings
  test/benchmark_random_interleaving_gtest.cc
  test/perf_counters_test.cc
  test/repetitions_test.cc
Labels: cla: yes
