Repository google/benchmark, pull requests merged in 2021-05, with the labels that each got.

#1127 Add `benchmark_context` flag that allows per-run custom context.
  README.md
  src/benchmark.cc
  src/commandlineflags.cc
  src/commandlineflags.h
  src/reporter.cc
  test/commandlineflags_gtest.cc
Labels: cla: yes

#1137 Add API to benchmark allowing for custom context to be added
  README.md
  include/benchmark/benchmark.h
  src/benchmark.cc
  src/json_reporter.cc
  src/reporter.cc
  test/benchmark_gtest.cc
Labels: cla: yes

#1141 cmake: Add explicit BENCHMARK_ENABLE_LIBPFM option
  CMakeLists.txt
Labels: cla: yes

#1142 Fix StrSplit empty string case
  src/string_util.cc
  test/string_util_gtest.cc
Labels: cla: yes

#1143 Cleanup Clang's -Wreserved-identifier instances
  include/benchmark/benchmark.h
  src/benchmark_register.cc
  src/mutex.h
  test/output_test.h
Labels: cla: yes

#1131 Add ubuntu-14.04 build and test workflow
  .github/workflows/build-and-test.yml
Labels: cla: yes

#1090 Add MSVC ARM64 support to cmake
  CMakeLists.txt
Labels: cla: yes

#1144 add g++-6 to ubuntu-14.04
  .github/workflows/build-and-test.yml
Labels: cla: yes

#1145 Remove travis configs that are covered by actions
  .travis.yml
Labels: cla: yes

#1153 [PFM] Extend perf counter support to multi-threaded cases.
  docs/perf_counters.md
  src/benchmark_runner.cc
  src/perf_counters.cc
  src/perf_counters.h
  test/perf_counters_gtest.cc
Labels: cla: yes

#1105 Implementation of random interleaving.
  README.md
  docs/random_interleaving.md
  src/benchmark.cc
  src/benchmark_adjust_repetitions.cc
  src/benchmark_adjust_repetitions.h
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_runner.cc
  src/benchmark_runner.h
  test/CMakeLists.txt
  test/benchmark_random_interleaving_gtest.cc
Labels: cla: yes, enhancement, next-release

#1047 fix version recorded in releases
  CMakeLists.txt
  cmake/GetGitVersion.cmake
  docs/releasing.md
Labels: cla: yes, next-release

#1156 Fix pedantic compilation flag violation
  CMakeLists.txt
  src/benchmark.cc
Labels: bug, cla: yes, next-release
