Repository google/benchmark, pull requests merged in 2021-04, with the labels that each got.

#1110 Shrink the tz_offset size to 41.
  src/timers.cc
Labels: cla: yes

#1111 Improve BENCHMARK_UNUSED definition
  include/benchmark/benchmark.h
Labels: cla: yes

#1109 Re-enable bazel without bazelisk and with scoped build/test targets
  .github/workflows/bazel.yml
Labels: cla: yes

#1113 Use fewer ramp up repetitions when KeepRunningBatch is used
  src/benchmark_runner.cc
  test/basic_test.cc
Labels: cla: yes

#1117 [sysinfo] Fix CPU Frequency reading on AMD Ryzen CPU's
  include/benchmark/benchmark.h
  src/sysinfo.cc
Labels: cla: yes

#1118 fix cmake issue with referencing a non-existing function argument
  cmake/AddCXXCompilerFlag.cmake
Labels: cla: yes

#1122 Add verbosity to CI logs
  .github/workflows/bazel.yml
  .github/workflows/build-and-test.yml
Labels: cla: yes

#1121 Fix windows warning on type conversion
  src/benchmark_register.h
Labels: bug, cla: yes

#1114 Support optional, user-directed collection of performance counters
  .github/workflows/build-and-test-perfcounters.yml
  CMakeLists.txt
  README.md
  cmake/Modules/FindPFM.cmake
  docs/perf_counters.md
  include/benchmark/benchmark.h
  src/CMakeLists.txt
  src/benchmark.cc
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_runner.cc
  src/benchmark_runner.h
  src/perf_counters.cc
  src/perf_counters.h
  src/string_util.cc
  src/string_util.h
  test/CMakeLists.txt
  test/perf_counters_gtest.cc
  test/perf_counters_test.cc
  test/string_util_gtest.cc
Labels: cla: yes, enhancement, next-release

#1128 Add multiple compiler support to build-and-test workflow
  .github/workflows/build-and-test.yml
Labels: cla: yes
