Repository google/benchmark, pull requests merged in 2021-11, with the labels that each got.

#1273 Fix errorWshorten-64-to-32 with clang 12.0
  test/basic_test.cc
Labels: cla: yes

#1272 Fix error with Fix Werror=old-style-cast
  src/benchmark.cc
  src/colorprint.cc
  src/console_reporter.cc
  test/user_counters_test.cc
Labels: cla: yes

#1274 Fixed typo in doc: s/marcro/macro
  docs/user_guide.md
Labels: cla: yes

#1276 Fix warning with MacOS
  src/timers.cc
Labels: cla: yes

#1280 clang-format Google on {src/,include/}
  include/benchmark/benchmark.h
  src/benchmark.cc
  src/benchmark_register.cc
  src/benchmark_register.h
  src/colorprint.cc
  src/commandlineflags.cc
  src/complexity.cc
  src/console_reporter.cc
  src/csv_reporter.cc
  src/cycleclock.h
  src/json_reporter.cc
  src/perf_counters.cc
  src/reporter.cc
  src/sleep.cc
  src/statistics.cc
  src/string_util.cc
  src/string_util.h
  src/sysinfo.cc
  src/timers.cc
Labels: cla: yes

#1282 format tests with clang-format
  test/args_product_test.cc
  test/basic_test.cc
  test/benchmark_test.cc
  test/clobber_memory_assembly_test.cc
  test/complexity_test.cc
  test/cxx03_test.cc
  test/diagnostics_test.cc
  test/donotoptimize_assembly_test.cc
  test/donotoptimize_test.cc
  test/filter_test.cc
  test/fixture_test.cc
  test/internal_threading_test.cc
  test/map_test.cc
  test/multiple_ranges_test.cc
  test/options_test.cc
  test/output_test.h
  test/output_test_helper.cc
  test/perf_counters_gtest.cc
  test/spec_arg_test.cc
  test/string_util_gtest.cc
  test/templated_fixture_test.cc
Labels: cla: yes

#1281 check clang format on pull requests and merges
  .github/workflows/clang-format-lint.yml
  include/benchmark/benchmark.h
  src/cycleclock.h
Labels: cla: yes

#1263 Fix dependency typo and unpin cibuildwheel version in wheel building …
  .github/workflows/wheels.yml
  docs/releasing.md
  setup.py
Labels: cla: yes, next-release

#1227 Support for building with LLVM clang-10/clang-11 on Windows.
  include/benchmark/benchmark.h
Labels: cla: yes

#1283 Remove bazelbuild/rules_cc dependency
  BUILD.bazel
  WORKSPACE
Labels: cla: yes

#1285 Googletest renamed master to main today.
  AUTHORS
  CONTRIBUTORS
  cmake/GoogleTest.cmake.in
Labels: cla: yes, next-release

#1269 Add Setup/Teardown option on Benchmark.
  docs/user_guide.md
  include/benchmark/benchmark.h
  src/benchmark_api_internal.cc
  src/benchmark_api_internal.h
  src/benchmark_register.cc
  src/benchmark_runner.cc
  test/CMakeLists.txt
  test/benchmark_setup_teardown_test.cc
Labels: cla: yes

#1286 disable lint check where we know it'd fail
  src/string_util.h
Labels: cla: yes

#1287 Disable clang-tidy (unused-using-decls)
  src/string_util.h
Labels: cla: yes

#1289 compare.py: compute and print 'OVERALL GEOMEAN' aggregate
  requirements.txt
  tools/gbench/report.py
Labels: cla: yes

#1290 Add clang-tidy check
  .clang-tidy
  .github/workflows/clang-tidy.yml
  AUTHORS
  CONTRIBUTORS
  cmake/GoogleTest.cmake
  src/string_util.cc
  test/skip_with_error_test.cc
Labels: cla: yes

#1291 Fix broken link to Setup/Teardown section
  docs/user_guide.md
Labels: cla: no
